# -*- coding: utf-8 -*-
"""
Harshita's Birthday Surprise Page with 3D Cake
"""

import streamlit as st
from datetime import datetime
import random
import os
from PIL import Image
import turtle

# --- Page Setup ---
st.set_page_config(
    page_title="Harshita's 21st Birthday!",
    page_icon="🎂",
    layout="centered"
)

# --- Paths ---
IMAGE_PATH = "MANCHURIAN.jpg"
PHOTO_DIR = "."  # All photos are in the repo root
SONG_PATH = "yt1z.net - Gryffin - Nobody Compares To You (Official Music Video) ft. Katie Pearlman (320 KBps).mp3"
CAKE_IMAGE = "cake.png"  # This will be generated by Turtle

# --- Constants ---
CORRECT_CODE = "2103"

# --- Initialize session state ---
if "unlocked" not in st.session_state:
    st.session_state.unlocked = False
if "audio_playing" not in st.session_state:
    st.session_state.audio_playing = False
    st.session_state.start_time = None
    st.session_state.audio_bytes = None
if "photo_index" not in st.session_state:
    st.session_state.photo_index = 0

# --- Dates ---
birthday = datetime(2025, 12, 21, 0, 0, 0)
now = datetime.now()
countdown = birthday - now

# --- Helper Functions ---
def show_landing_page():
    st.markdown("<h1 style='text-align: center; color: #D6336C;'>🎉 Harshita's 21st Birthday 🎉</h1>", unsafe_allow_html=True)
    st.markdown("<h3 style='text-align: center; color: #F25F5C;'>Countdown to Your Special Day</h3>", unsafe_allow_html=True)

    if countdown.total_seconds() > 0:
        days = countdown.days
        hours = countdown.seconds // 3600
        minutes = (countdown.seconds % 3600) // 60
        st.markdown(
            f"<h2 style='text-align: center; color: #FF6F91;'>"
            f"{days} day{'s' if days != 1 else ''}, {hours} hour{'s' if hours != 1 else ''}, and {minutes} minute{'s' if minutes != 1 else ''} left!"
            f"</h2>", unsafe_allow_html=True)
    else:
        st.markdown("<h2 style='text-align: center; color: #FF6F91;'>🎂 Today is your day! Happy 21st Birthday! 🎂</h2>", unsafe_allow_html=True)
        st.balloons()

    st.markdown("---")
    st.markdown("<h3 style='text-align: center;'>🔐 Enter the Secret Code to Unlock a Surprise</h3>", unsafe_allow_html=True)

    code_input = st.text_input("🔢 Enter 4-digit Secret Code", type="password", max_chars=4)

    if code_input:
        if code_input == CORRECT_CODE:
            st.success("🔓 Unlocked! You're amazing for figuring it out. 💖")
            st.session_state.unlocked = True
            st.experimental_rerun()  # rerun after unlocking
        else:
            st.error("❌ That's not the right code. Try again?")

    # Show initial image
    if os.path.exists(IMAGE_PATH):
        image = Image.open(IMAGE_PATH)
        st.markdown("---")
        st.image(image, caption="Your Favourite 😉", use_column_width=True)
    else:
        st.warning("Couldn't find MANCHURIAN.jpg in the repo.")

def show_menu():
    menu_html = """
    <div style='background-color:#ADD8E6; padding:15px; border-radius:10px; text-align:center; font-family:"Comic Sans MS", cursive;'>
        <h3>💌 Choose Your Surprise 💌</h3>
    </div>
    """
    st.markdown(menu_html, unsafe_allow_html=True)
    choice = st.radio("", ("Love Letter", "Photo Slideshow + Song", "See Cake"))
    return choice

def show_love_letter():
    # ... (Your long love letter here)
    st.markdown("<h3 style='color:#6A0572;'>A Love Letter Just For You</h3>", unsafe_allow_html=True)
    love_letter = """Your heartfelt love letter here."""
    st.write(love_letter)

def show_slideshow():
    photos = sorted([f for f in os.listdir(PHOTO_DIR) if f.lower().endswith((".jpg", ".jpeg", ".png", ".gif"))])
    if photos:
        total_photos = len(photos)
        song_length_seconds = 231
        photo_display_time = song_length_seconds / total_photos
        if not st.session_state.audio_playing:
            if st.button("▶️ Play Song"):
                st.session_state.audio_playing = True
                st.session_state.start_time = datetime.now()
                with open(SONG_PATH, "rb") as f:
                    st.session_state.audio_bytes = f.read()
        else:
            elapsed = (datetime.now() - st.session_state.start_time).total_seconds()
            st.audio(st.session_state.audio_bytes, format="audio/mp3", start_time=elapsed)

        elapsed = (datetime.now() - st.session_state.start_time).total_seconds() if st.session_state.audio_playing else 0
        st.session_state.photo_index = int(elapsed // photo_display_time) % total_photos
        image_path = os.path.join(PHOTO_DIR, photos[st.session_state.photo_index])
        img = Image.open(image_path)
        st.image(img, use_column_width=True)
        st.markdown(f"<p style='text-align: center; color: gray;'>Photo {st.session_state.photo_index + 1} of {total_photos}</p>", unsafe_allow_html=True)
    else:
        st.info("No photos found for the slideshow.")

def draw_cake_image():
    """Draw 3D Triple Chocolate Cake using Turtle and save as PNG"""
    screen = turtle.Screen()
    screen.setup(width=600, height=500)
    screen.bgcolor("#FFE4C4")
    t = turtle.Turtle()
    t.hideturtle()
    t.speed(0)

    ingredients = {
        "dark chocolate": "#2A1506",
        "milk chocolate": "#BF671F",
        "white chocolate": "#FFFDC4",
        "icing sugar": "#FFFFFF",
        "cherry": "#C20067",
        "shadow": "#A0522D"
    }

    layers = [["dark chocolate", 40], ["milk chocolate", 50], ["white chocolate", 40]]
    x, y = -120, -140
    width = 240
    depth = 20

    def draw_3d_layer(t, color, x, y, width, height, depth):
        t.penup()
        t.goto(x, y)
        t.pendown()
        t.fillcolor(color)
        t.begin_fill()
        for _ in range(2):
            t.forward(width)
            t.left(90)
            t.forward(height)
            t.left(90)
        t.end_fill()
        t.fillcolor(ingredients["shadow"])
        t.begin_fill()
        t.goto(x, y + height)
        t.goto(x + depth, y + height + depth / 2)
        t.goto(x + width + depth, y + height + depth / 2)
        t.goto(x + width, y + height)
        t.goto(x, y + height)
        t.end_fill()

    def draw_3d_ellipse(t, color, x, y, width, height):
        t.penup()
        t.goto(x, y - height / 2)
        t.pendown()
        t.fillcolor(color)
        t.begin_fill()
        for i in range(360):
            angle = i * 3.14159 / 180
            px = width / 2 * math.cos(angle)
            py = height / 2 * math.sin(angle)
            t.goto(x + px, y + py)
        t.end_fill()

    def add_cherry(t, x, y, radius):
        t.penup()
        t.goto(x, y - radius)
        t.pendown()
        t.fillcolor(ingredients["cherry"])
        t.begin_fill()
        t.circle(radius)
        t.end_fill()

    def add_icing(t, x, y, width):
        t.penup()
        t.goto(x - width / 2, y)
        t.pendown()
        t.fillcolor(ingredients["icing sugar"])
        t.begin_fill()
        for dx in range(-width // 2, width // 2):
            t.goto(x + dx, y + 10 * math.cos(dx / 20))
        t.goto(x + width / 2, y)
        t.goto(x - width / 2, y)
        t.end_fill()

    for layer in layers:
        draw_3d_layer(t, ingredients[layer[0]], x, y, width, layer[1], depth)
        y += layer[1]

    draw_3d_ellipse(t, ingredients["white chocolate"], x + width / 2, y, width, 20)
    add_icing(t, x + width / 2, y, width)
    add_cherry(t, x + width / 2, y + 15, 15)

    ts = t.getscreen()
    ts.getcanvas().postscript(file="cake.eps")  # save as EPS
    from PIL import Image as PILImage
    img = PILImage.open("cake.eps")
    img.save(CAKE_IMAGE, "png")
    turtle.bye()  # close turtle

def show_cake():
    if not os.path.exists(CAKE_IMAGE):
        draw_cake_image()
    cake_img = Image.open(CAKE_IMAGE)
    st.image(cake_img, caption="🎂 Triple Chocolate 3D Cake 🎂", use_column_width=True)

# --- Main ---
if st.session_state.unlocked:
    choice = show_menu()
    if choice == "Love Letter":
        show_love_letter()
    elif choice == "Photo Slideshow + Song":
        show_slideshow()
    elif choice == "See Cake":
        show_cake()
else:
    show_landing_page()
